name: Sourcemeta
description: Continuous Integration

runs:
  using: composite
  steps:
    - uses: actions/checkout@v4

    # ClangFormat
    - if: runner.os == 'windows'
      shell: pwsh
      run: pip install clang-format==18.1.5
    - if: runner.os != 'windows'
      shell: bash
      run: pip install clang-format==18.1.5

    # Brewfile
    - if: runner.os == 'macos'
      run: if [ -f Brewfile ]; then brew bundle; fi
      shell: bash
      env:
        HOMEBREW_NO_ANALYTICS: 1
        HOMEBREW_NO_AUTO_UPDATE: 1

    # ShellCheck
    - if: runner.os == 'windows'
      shell: pwsh
      run: choco install shellcheck

    # CMake
    - run: cmake --version
      if: runner.os == 'windows'
      shell: pwsh
    - run: cmake --version
      if: runner.os != 'windows'
      shell: bash
