name: Sourcemeta
description: Continuous Integration

inputs:
  step:
    description: Step to run
    required: true
  mode:
    description: Static vs shared
    required: false
    default: static
  compiler:
    description: The compiler identifier
    required: false
    default: ''
  options:
    description: Additional CMake options
    required: false
    default: ''
  component:
    description: CMake component
    required: false
    default: ''
  clang_format:
    description: Run ClangFormat
    required: false
    default: true

runs:
  using: composite
  steps:
    #############################################
    # Dependencies
    #############################################

    # ClangFormat
    - if: runner.os == 'windows' && inputs.step == 'dependencies'
      shell: pwsh
      run: pip install clang-format==18.1.5
    - if: runner.os != 'windows' && inputs.step == 'dependencies'
      shell: bash
      run: pip install clang-format==18.1.5

    # Dependencies & Brewfile
    - if: runner.os == 'macos' && inputs.step == 'dependencies'
      run: brew install cmake doxygen && if [ -f Brewfile ]; then brew bundle; fi
      shell: bash
      env:
        HOMEBREW_NO_ANALYTICS: 1
        HOMEBREW_NO_AUTO_UPDATE: 1

    # Dependencies
    - if: runner.os == 'linux' && inputs.step == 'dependencies'
      shell: bash
      run: sudo apt update && sudo apt install -y doxygen

    # ShellCheck
    - if: runner.os == 'windows' && inputs.step == 'dependencies'
      shell: pwsh
      run: choco install shellcheck

    #############################################
    # Configure
    #############################################

    - if: runner.os == 'windows' && inputs.step == 'configure'
      run: cmake --version
      shell: pwsh
    - if: runner.os != 'windows' && inputs.step == 'configure'
      run: cmake --version
      shell: bash

    - if: runner.os == 'windows' && inputs.step == 'configure' && inputs.mode == 'static' && inputs.compiler == 'msvc'
      shell: pwsh
      run: >
        cmake -S . -B ./build
        -DCMAKE_BUILD_TYPE:STRING=Release
        -DBUILD_SHARED_LIBS:BOOL=OFF
        -DCMAKE_COMPILE_WARNING_AS_ERROR:BOOL=ON
        ${{ inputs.options }}
    - if: runner.os == 'windows' && inputs.step == 'configure' && inputs.mode == 'shared' && inputs.compiler == 'msvc'
      shell: pwsh
      run: >
        cmake -S . -B ./build
        -DCMAKE_BUILD_TYPE:STRING=Release
        -DBUILD_SHARED_LIBS:BOOL=ON
        -DCMAKE_COMPILE_WARNING_AS_ERROR:BOOL=ON
        ${{ inputs.options }}

    - if: runner.os != 'windows' && inputs.step == 'configure' && inputs.mode == 'static' && inputs.compiler == 'llvm'
      shell: bash
      run: >
        cmake -S . -B ./build
        -DCMAKE_BUILD_TYPE:STRING=Release
        -DBUILD_SHARED_LIBS:BOOL=OFF
        -DCMAKE_COMPILE_WARNING_AS_ERROR:BOOL=ON
        ${{ inputs.options }}
      env:
        CC: clang
        CXX: clang++
    - if: runner.os != 'windows' && inputs.step == 'configure' && inputs.mode == 'shared' && inputs.compiler == 'llvm'
      shell: bash
      run: >
        cmake -S . -B ./build
        -DCMAKE_BUILD_TYPE:STRING=Release
        -DBUILD_SHARED_LIBS:BOOL=ON
        -DCMAKE_COMPILE_WARNING_AS_ERROR:BOOL=ON
        ${{ inputs.options }}
      env:
        CC: clang
        CXX: clang++

    - if: runner.os != 'windows' && inputs.step == 'configure' && inputs.mode == 'static' && inputs.compiler == 'gcc'
      shell: bash
      run: >
        cmake -S . -B ./build
        -DCMAKE_BUILD_TYPE:STRING=Release
        -DBUILD_SHARED_LIBS:BOOL=OFF
        -DCMAKE_COMPILE_WARNING_AS_ERROR:BOOL=ON
        ${{ inputs.options }}
      env:
        CC: gcc
        CXX: g++
    - if: runner.os != 'windows' && inputs.step == 'configure' && inputs.mode == 'shared' && inputs.compiler == 'gcc'
      shell: bash
      run: >
        cmake -S . -B ./build
        -DCMAKE_BUILD_TYPE:STRING=Release
        -DBUILD_SHARED_LIBS:BOOL=ON
        -DCMAKE_COMPILE_WARNING_AS_ERROR:BOOL=ON
        ${{ inputs.options }}
      env:
        CC: gcc
        CXX: g++

    #############################################
    # Build
    #############################################

    - if: runner.os == 'windows' && inputs.step == 'build'
      shell: pwsh
      run: cmake --build ./build --config Release --parallel 4
    - if: runner.os != 'windows' && inputs.step == 'build'
      shell: bash
      run: cmake --build ./build --config Release --parallel 4

    # TODO: Revert this when possible
    - name: Copy in the correct VC runtime DLLs (workaround for actions/runner-images#10004)
      if: runner.os == 'windows' && inputs.step == 'build'
      shell: pwsh
      run: |
        Copy-Item (Join-Path `
          ((Get-ChildItem -Directory `
              -Path "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Redist\MSVC\14.*" |
            Sort -Descending | Select-Object -First 1).FullName
          ) 'x64\Microsoft.VC143.CRT\*.dll') "build\bin\Release"

    #############################################
    # Check
    #############################################

    # ClangFormat
    - if: runner.os == 'windows' && inputs.step == 'check' && inputs.clang_format
      shell: pwsh
      run: cmake --build ./build --config Release --target clang_format_test
    - if: runner.os != 'windows' && inputs.step == 'check' && inputs.clang_format
      shell: bash
      run: cmake --build ./build --config Release --target clang_format_test

    #############################################
    # Install
    #############################################

    - if: runner.os == 'windows' && inputs.step == 'install'
      shell: pwsh
      run: >
        cmake --install ./build --prefix ./build/dist --config Release --verbose
        --component sourcemeta_${{ inputs.component }}
    - if: runner.os == 'windows' && inputs.step == 'install'
      shell: pwsh
      run: >
        cmake --install ./build --prefix ./build/dist --config Release --verbose
        --component sourcemeta_${{ inputs.component }}_dev
    - if: runner.os != 'windows' && inputs.step == 'install'
      shell: bash
      run: >
        cmake --install ./build --prefix ./build/dist --config Release --verbose
        --component sourcemeta_${{ inputs.component }}
    - if: runner.os != 'windows' && inputs.step == 'install'
      shell: bash
      run: >
        cmake --install ./build --prefix ./build/dist --config Release --verbose
        --component sourcemeta_${{ inputs.component }}_dev

    #############################################
    # Test
    #############################################

    # Not every CTest version supports the --test-dir option. If such option
    # is not recognized, `ctest` will successfully exit finding no tests.
    # Better to be sure and `cd` all the time here.
    - if: runner.os == 'windows' && inputs.step == 'test'
      shell: pwsh
      run: cd ./build && ctest --build-config Release --output-on-failure --parallel
    - if: runner.os != 'windows' && inputs.step == 'test'
      shell: bash
      run: cd ./build && ctest --build-config Release --output-on-failure --parallel
      env:
        # See https://clang.llvm.org/docs/UndefinedBehaviorSanitizer.html
        UBSAN_OPTIONS: print_stacktrace=1

    #############################################
    # Doxygen
    #############################################

    - if: runner.os == 'windows' && inputs.step == 'doxygen'
      shell: pwsh
      run: cmake --build ./build --config Release --target doxygen
    - if: runner.os != 'windows' && inputs.step == 'doxygen'
      shell: bash
      run: cmake --build ./build --config Release --target doxygen

    #############################################
    # Website
    #############################################

    - name: Setup Pages
      if: inputs.step == 'website'
      uses: actions/configure-pages@v1
    - name: Upload artifact
      if: inputs.step == 'website'
      uses: actions/upload-pages-artifact@v1
      with:
        path: ./build/website
    - name: Deploy to GitHub Pages
      if: inputs.step == 'website'
      id: deployment
      uses: actions/deploy-pages@v2

    #############################################
    # Unikraft
    #############################################

    - uses: unikraft/kraftkit@stable
      if: inputs.step == 'unikraft'
      with:
        workdir: .
        run: |
          kraft build --target development --jobs 4 --log-type=basic unikraft
          kraft run --target development --disable-acceleration unikraft --memory 128Mi
