name: Noa

on:
  schedule:
    # Once per day, Monday to Friday
    - cron: '0 19 * * 1-5'
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        platform:
          - os: macos-latest
            cc: clang
            cxx: clang++
            type: static
            shell: sh
          - os: macos-latest
            cc: clang
            cxx: clang++
            type: shared
            shell: sh
          - os: macos-latest
            cc: gcc-13
            cxx: g++-13
            type: static
            shell: sh
          - os: ubuntu-latest
            cc: clang
            cxx: clang++
            type: static
            shell: sh
          - os: ubuntu-latest
            cc: gcc
            cxx: g++
            type: static
            shell: sh
          - os: ubuntu-latest
            cc: clang
            cxx: clang++
            type: shared
            shell: sh
          - os: ubuntu-latest
            cc: gcc
            cxx: g++
            type: shared
            shell: sh
          - os: windows-latest
            type: static
            shell: pwsh
          - os: windows-latest
            type: shared
            shell: pwsh

    defaults:
      run:
        shell: ${{ matrix.platform.shell }}

    runs-on: ${{ matrix.platform.os }}
    env:
      CC: ${{ matrix.platform.cc }}
      CXX: ${{ matrix.platform.cxx }}
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies (macOS)
        if: runner.os == 'macos'
        run: brew bundle
        env:
          HOMEBREW_NO_ANALYTICS: 1
          HOMEBREW_NO_AUTO_UPDATE: 1
      - run: cmake --version
      - name: Configure Noa (static)
        if: matrix.platform.type == 'static'
        run: >
          cmake -Wno-dev -S . -B ./build
          -DCMAKE_BUILD_TYPE:STRING=Release
          -DBUILD_SHARED_LIBS:BOOL=OFF
          -DCMAKE_COMPILE_WARNING_AS_ERROR:BOOL=ON
          ${{ matrix.platform.options }}
      - name: Configure Noa (shared)
        if: matrix.platform.type == 'shared'
        run: >
          cmake -Wno-dev -S . -B ./build
          -DCMAKE_BUILD_TYPE:STRING=Release
          -DBUILD_SHARED_LIBS:BOOL=ON
          -DCMAKE_COMPILE_WARNING_AS_ERROR:BOOL=ON
          ${{ matrix.platform.options }}
      - run: cmake --build ./build --config Release --parallel 4
