name: website
on:
  pull_request:

concurrency:
  group: website-build-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: sudo apt update
      - run: sudo apt install -y doxygen
      - run: >
          cmake -S . -B ./build
          -DCMAKE_BUILD_TYPE:STRING=Release
          -DNOA_HASH:BOOL=OFF
          -DNOA_FLAT_MAP:BOOL=OFF
          -DNOA_GOOGLETEST:BOOL=OFF
          -DNOA_GOOGLEBENCHMARK:BOOL=OFF
          -DNOA_DOCS:BOOL=ON
      - run: cmake --build ./build --config Release --target doxygen
